#!/usr/bin/env bash
set -e

# ------- Configurations -------
# XXX: Users can adjust this part for their own purpose.

# Docker image tag
IMAGE_NAME=nix-dev:latest

# To speed up nix installation:
# Nix installer URL
NIX_INSTALL_URL=https://mirrors.tuna.tsinghua.edu.cn/nix/latest/install
# Nixpkgs channel URL
NIX_CHANNEL_URL=https://mirrors.tuna.tsinghua.edu.cn/nix-channels/nixpkgs-unstable
# Nix binary cache substituters (space-separated)
NIX_CACHE_SUBSTITUTERS="https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store https://cache.nixos.org"

# ------- Build Docker Image -------
# XXX: Users shall not modify this part.

# Create a temporal directory
DIR=$(mktemp -d)

# Generate Dockerfile
cat << DOCKER_EOF > "$DIR/Dockerfile"
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install base dependencies
RUN apt-get update && apt-get install -y \
    curl git xz-utils ca-certificates locales \
    && rm -rf /var/lib/apt/lists/*

# Configure locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Create dev user and ensure it has correct permission.
# Note: Docker volumes store file ownership by UID number, not username.
#   If this auto-assigned UID (e.g., dev:1000) matches a host user's UID
#   (e.g., hostuser:1000), that host user can directly read/write the files
#   written by dev user, even though the files belong to the container's
#   dev user conceptually. And vice versa.
# We insert the host user's UID by $(id -u).
# The -u flag explicitly sets the container UID to match the host, ensuring
# Docker volume files are directly accessible on the host without root.
RUN useradd -m -s /bin/bash -u $(id -u) dev

# Copy entrypoint script
COPY init.sh /home/dev/init.sh
RUN chown dev:dev /home/dev/init.sh && chmod +x /home/dev/init.sh

# Switch to unprivileged user
USER dev
ENV USER=dev
WORKDIR /home/dev

# Pre-configure Nix (enable Flakes + mirror substituters)
RUN mkdir -p /home/dev/.config/nix && \
    echo "experimental-features = nix-command flakes" > /home/dev/.config/nix/nix.conf && \
    echo "substituters = ${NIX_CACHE_SUBSTITUTERS}" >> /home/dev/.config/nix/nix.conf

ENV PATH=/home/dev/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ENTRYPOINT ["/bin/bash", "/home/dev/init.sh"]
CMD ["bash"]
DOCKER_EOF

# Generate init.sh (container entrypoint script)
cat << INIT_EOF > "$DIR/init.sh"
#!/bin/bash
set -e

# Install/restore Nix core
if [ ! -L "/nix/var/nix/profiles/per-user/dev/profile" ]; then
    echo ">>> [Install] Setting up Nix Profile..."
    mkdir -p "/nix/var/nix/profiles/per-user/dev"

    # Try to find existing Nix package in store
    NIX_PATH=\$(ls -d /nix/store/*-nix-2.* 2>/dev/null | grep -v '\.patch' | grep -v 'nixpkgs' | head -n 1)

    if [ ! -z "\$NIX_PATH" ] && [ -d "\$NIX_PATH" ]; then
        # Store has data, restore profile links
        echo ">>> Found existing Nix in store, restoring profile..."
        ln -sf "\$NIX_PATH" "/nix/var/nix/profiles/per-user/dev/profile-1-link"
        ln -sf "/nix/var/nix/profiles/per-user/dev/profile-1-link" "/nix/var/nix/profiles/per-user/dev/profile"
        # Generate manifest.nix so that nix profile list can recognize it
        echo "[{ outPath = \"\$NIX_PATH\"; attrPath = [\"nix\"]; }]" > "/nix/var/nix/profiles/per-user/dev/manifest.nix"
    else
        # Fresh installation
        echo ">>> Performing fresh installation..."
        curl -L ${NIX_INSTALL_URL} | sh -s -- --no-daemon
        # Persist profile generated by official installer
        if [ -L "/home/dev/.nix-profile" ]; then
            mv "/home/dev/.nix-profile" "/nix/var/nix/profiles/per-user/dev/profile"
            if [ -f "/home/dev/.nix-profile/manifest.nix" ]; then
                mv "/home/dev/.nix-profile/manifest.nix" "/nix/var/nix/profiles/per-user/dev/manifest.nix"
            fi
        fi
    fi
else
    echo ">>> [Restore] Nix profile found."
fi

# Configure user environment
# Ensure ~/.nix-profile always points to the persistent profile under /nix
ln -sf "/nix/var/nix/profiles/per-user/dev/profile" "/home/dev/.nix-profile"
# Load environment variables
if [ -e "/home/dev/.nix-profile/etc/profile.d/nix.sh" ]; then
    . "/home/dev/.nix-profile/etc/profile.d/nix.sh"
fi

# Configure Nix channels
if ! nix-channel --list | grep -q "nixpkgs"; then
    echo ">>> Adding nixpkgs channel..."
    nix-channel --add ${NIX_CHANNEL_URL} nixpkgs
    nix-channel --update
fi

# Configure Flakes
mkdir -p "/home/dev/.config/nix"
if [ ! -f "/home/dev/.config/nix/nix.conf" ]; then
    cat > "/home/dev/.config/nix/nix.conf" << EOF
experimental-features = nix-command flakes
substituters = ${NIX_CACHE_SUBSTITUTERS}
EOF
fi

# Write auto-load into .bashrc
if ! grep -q "Nix Profile" "/home/dev/.bashrc" 2>/dev/null; then
    echo "" >> "/home/dev/.bashrc"
    echo "# Nix Profile" >> "/home/dev/.bashrc"
    echo "if [ -e /home/dev/.nix-profile/etc/profile.d/nix.sh ]; then . /home/dev/.nix-profile/etc/profile.d/nix.sh; fi" >> "/home/dev/.bashrc"
fi

exec "\$@"
INIT_EOF

chmod +x "$DIR/init.sh"

# Build Docker image
docker build -t "$IMAGE_NAME" "$DIR"

# Remove intermediate artifacts
rm "$DIR/Dockerfile" "$DIR/init.sh"
