#!/usr/bin/env bash
set -e

# Load .env configuration
DIR="$(cd "$(dirname "$0")" && pwd)"
source "$DIR/.env"

# Generate Dockerfile
# \${VAR} — expanded at build time (from .env), Dockerfile has no runtime variables
cat << DOCKER_EOF > "$DIR/Dockerfile"
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install base dependencies
RUN apt-get update && apt-get install -y \
    curl git xz-utils ca-certificates locales \
    && rm -rf /var/lib/apt/lists/*

# Configure locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Create dev user and pre-create /nix directory, ensure dev user has write permission after volume mount
RUN useradd -m -s /bin/bash ${DEV_USER} && \
    mkdir -m 0755 ${NIX_STORE_DIR} && \
    chown ${DEV_USER}:${DEV_USER} ${NIX_STORE_DIR}

# Copy entrypoint script
COPY init.sh /home/${DEV_USER}/init.sh
RUN chown ${DEV_USER}:${DEV_USER} /home/${DEV_USER}/init.sh && chmod +x /home/${DEV_USER}/init.sh

# Switch to unprivileged user
USER ${DEV_USER}
ENV USER=${DEV_USER}
WORKDIR /home/${DEV_USER}

# Pre-configure Nix (enable Flakes + mirror substituters)
RUN mkdir -p /home/${DEV_USER}/.config/nix && \
    echo "experimental-features = nix-command flakes" > /home/${DEV_USER}/.config/nix/nix.conf && \
    echo "substituters = ${NIX_CACHE_SUBSTITUTERS}" >> /home/${DEV_USER}/.config/nix/nix.conf

ENV PATH=/home/${DEV_USER}/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ENTRYPOINT ["/bin/bash", "/home/${DEV_USER}/init.sh"]
CMD ["bash"]
DOCKER_EOF

# Generate init.sh (container entrypoint script)
# \${VAR} — expanded at build time (from .env), \$VAR — runtime reference (init.sh internal variable, not expanded)
cat << INIT_EOF > "$DIR/init.sh"
#!/bin/bash
set -e

# Install/restore Nix core
if [ ! -L "${NIX_STORE_DIR}/var/nix/profiles/per-user/${DEV_USER}/profile" ]; then
    echo ">>> [Install] Setting up Nix Profile..."
    mkdir -p "${NIX_STORE_DIR}/var/nix/profiles/per-user/${DEV_USER}"

    # Try to find existing Nix package in store
    NIX_STORE_PATH=\$(ls -d ${NIX_STORE_DIR}/store/*-nix-2.* 2>/dev/null | grep -v '\.patch' | grep -v 'nixpkgs' | head -n 1)

    if [ ! -z "\$NIX_STORE_PATH" ] && [ -d "\$NIX_STORE_PATH" ]; then
        # Store has data, restore profile links
        echo ">>> Found existing Nix in store, restoring profile..."
        ln -sf "\$NIX_STORE_PATH" "${NIX_STORE_DIR}/var/nix/profiles/per-user/${DEV_USER}/profile-1-link"
        ln -sf "${NIX_STORE_DIR}/var/nix/profiles/per-user/${DEV_USER}/profile-1-link" "${NIX_STORE_DIR}/var/nix/profiles/per-user/${DEV_USER}/profile"
        # Generate manifest.nix so that nix profile list can recognize it
        echo "[{ outPath = \"\$NIX_STORE_PATH\"; attrPath = [\"nix\"]; }]" > "${NIX_STORE_DIR}/var/nix/profiles/per-user/${DEV_USER}/manifest.nix"
    else
        # Fresh installation
        echo ">>> Performing fresh installation..."
        curl -L ${NIX_INSTALL_URL} | sh -s -- --no-daemon
        # Persist profile generated by official installer
        if [ -L "/home/${DEV_USER}/.nix-profile" ]; then
            mv "/home/${DEV_USER}/.nix-profile" "${NIX_STORE_DIR}/var/nix/profiles/per-user/${DEV_USER}/profile"
            if [ -f "/home/${DEV_USER}/.nix-profile/manifest.nix" ]; then
                mv "/home/${DEV_USER}/.nix-profile/manifest.nix" "${NIX_STORE_DIR}/var/nix/profiles/per-user/${DEV_USER}/manifest.nix"
            fi
        fi
    fi
else
    echo ">>> [Restore] Nix profile found."
fi

# Configure user environment
# Ensure ~/.nix-profile always points to the persistent profile under /nix
ln -sf "${NIX_STORE_DIR}/var/nix/profiles/per-user/${DEV_USER}/profile" "/home/${DEV_USER}/.nix-profile"
# Load environment variables
if [ -e "/home/${DEV_USER}/.nix-profile/etc/profile.d/nix.sh" ]; then
    . "/home/${DEV_USER}/.nix-profile/etc/profile.d/nix.sh"
fi

# Configure Nix channels
if ! nix-channel --list | grep -q "nixpkgs"; then
    echo ">>> Adding nixpkgs channel..."
    nix-channel --add ${NIX_CHANNEL_URL} nixpkgs
    nix-channel --update
fi

# Configure Flakes
mkdir -p "/home/${DEV_USER}/.config/nix"
if [ ! -f "/home/${DEV_USER}/.config/nix/nix.conf" ]; then
    cat > "/home/${DEV_USER}/.config/nix/nix.conf" << EOF
experimental-features = nix-command flakes
substituters = ${NIX_CACHE_SUBSTITUTERS}
EOF
fi

# Write auto-load into .bashrc
if ! grep -q "Nix Profile" "/home/${DEV_USER}/.bashrc" 2>/dev/null; then
    echo "" >> "/home/${DEV_USER}/.bashrc"
    echo "# Nix Profile" >> "/home/${DEV_USER}/.bashrc"
    echo "if [ -e /home/${DEV_USER}/.nix-profile/etc/profile.d/nix.sh ]; then . /home/${DEV_USER}/.nix-profile/etc/profile.d/nix.sh; fi" >> "/home/${DEV_USER}/.bashrc"
fi

exec "\$@"
INIT_EOF

chmod +x "$DIR/init.sh"

# Build Docker image
docker build -t "$IMAGE_NAME" "$DIR"

# Remove intermediate artifacts
rm "$DIR/Dockerfile" "$DIR/init.sh"
